# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: 'init'
    backendServiceArm: 'Free Trial(71c53708-e6f7-4280-a395-e01f69930a42)'
    backendAzureRmResourceGroupName: 'myrsg'
    backendAzureRmStorageAccountName: 'mystorage683i9'
    backendAzureRmContainerName: 'tfstorage'
    backendAzureRmKey: 'dev.terraform.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV1@1
  inputs:
    provider: 'azurerm'
    command: 'plan'
    backendServiceArm: 'Free Trial(71c53708-e6f7-4280-a395-e01f69930a42)'
- task: TerraformTaskV1@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    backendServiceArm: 'Free Trial(71c53708-e6f7-4280-a395-e01f69930a42)'